"CREATE DATABASE jeuDeRole";

"CREATE TABLE users (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(30) NOT NULL,
  email VARCHAR(30) NOT NULL,
  psswrd VARCHAR(255) NOT NULL,
  age INT UNSIGNED NOT NULL
  )";
  
  "CREATE TABLE game (
  gameID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255)
  )";

 "CREATE TABLE gamePlayers (
  login VARCHAR(255), 
  FOREIGN KEY (login) REFERENCES users(login),
  name VARCHAR(255), 
  FOREIGN KEY (name) REFERENCES game(name)
  )";


  
